### ISSUE TITLE
Support multiple Chargebee Sites

### ISSUE THREAD

**Issue by gerbal** [WTTJ/chargebeex#68]
It's possible to have multiple chargebee sites in a single application. 

I suggest implementing a per-site configuration struct, similar to how ecto databases can be handled. I'm highly ambivalent about the ergonomics here.

```elixir
defmodule MyChargebeeSite do
   use Chargebeex.Site
end

config :chargebeex, MyChargebeeSite, 
	namespace: "my_namespace",
    api_key: "myapi_key"

# option 1
customers =  Chargebeex.Customer.retrieve(MyChargebeeSite, "foobar")

# option 2
customers = MyChargebeeSite.Customer.retrieve("foobar")

#option 3
customers = MyChargebeeSite.exec(Chargebeex.Customer.retrieve("foobar")
```

Option 2 is probably the least disruptive to existing usage of Chargebeex

**Comment by maximemenager** [comment]
Hi @gerbal ! Thanks for your issue, I also think the option 2 is the best solution. I don't have many time at the moment, feel free to start a PR ;)
